### ISSUE TITLE
ArgumentError while OrderSend

### ISSUE THREAD

**Issue by SarunasSS** [rmawatson/PyMT4#12]
I am trying to use PyMT4, but am experiencing some issues. In the example I've changed the function to the following:

`def OnTickHandler(symbol, bid, ask):
    print symbol, bid, ask
    OrderSend(symbol, OP_BUY, 0.01, ask, 5, 0.0, 0.0, "TestComment")` 

When I run I get the following error:
    ` File "C:\Users\WorkerBee\Downloads\PyMT4-master\PyMT4-master\PyMT4_example.py", line 102, in OnTickHandler
    OrderSend(symbol, 0, 0.01, ask, 5, 0.0, 0.0, "Test")
Boost.Python.ArgumentError: Python argument types in
    PyMT4.OrderSend(str, int, float, float, int, float, float, str)
did not match C++ signature:
    OrderSend(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, int, double, double, int, double, double, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >, int, int, int)`

Could you help me with that?

My system:
    Windows 8.1 x64
    Python 2.7.11 32bit
    Installed vcredist_x86
    pymt4_host on one EURUSD window
    pymt4_ontick on another EURUSD window

**Comment by rmawatson** [comment]
Yea, so your argument types are wrong to the Function. by the looks of it your missing the last 3 ints, although there are defaults set in C++, and in the original MT4, I have not set up the python bindings to have default arguments. There is alot of work done wrapping the rest of the api. I will make sure defaults are set in python aswell.

For now just specify the defaults for the last 3 aqrgs

   int      magic=0,             // magic number
   datetime expiration=0,        // pending order expiration
   color    arrow_color=clrNONE  // color

**Comment by SarunasSS** [comment]
That helped solved this issue. Note the color has to be VALUE_CLR_NONE.
Now I'm getting the following error and pymt4_host dies on me:

`2016.02.17 04:27:34.909 Access violation read to 0x0B009000 in 'C:\Users\WorkerBee\AppData\Roaming\MetaQuotes\Terminal\7906D2EE81B3BF349C385CABF5F6EFA6\MQL4\Libraries\pymt4.dll'`

**Comment by rmawatson** [comment]
Try now. Not looked at the code in years. But have just spent today doing a pass. Should be better.
