### ISSUE TITLE
MarketInfo(), iOpen() not working

### ISSUE THREAD

**Issue by bilalmahmood1** [rmawatson/PyMT4#13]
When I try to run these functions in the example code that comes with this package, my MT4 crashes.
Moreover, I am not able to access my current prices that are being displayed on my market watch.
It would be great if you can give me some pointers on why that is happening. Moreover, I was successful in getting information like how many trades are opened, their IDs, their symbol etc,

for example: the code below does't return prices when I use it. Is it possible that I could access 
real time prices?

if __name__ == "__main__":
    
    print Connect()
    OnOrderManager.Initialize()
    RegisterOnOrderHandler(OnOrderHandler)
    RegisterOnTickHandler("*",OnTickHandler)
    print iOpen(OrderSymbol(4227589),PERIOD_MN1,1) #<<<<<<<(returns 0.0 instead of actual price)

    try:
        while(True):
            
            time.sleep(0.5)
    except KeyboardInterrupt:
        pass
    
    
    OnOrderManager.Shutdown()
    Disconnect()

thanks in advance.

**Comment by fjfzzl** [comment]
i also so.  i  hope author give us some sample code, so we can learn from them.

can someone help us?

thank you!
