### ISSUE TITLE
this project code is not the latest, can someone give me the newer code?

### ISSUE THREAD

**Issue by fjfzzl** [rmawatson/PyMT4#14]
this project code is not the latest, can the author or someone give me the newer code? my email: fjfzzl [at] fjfzzl.com ,thank you very much!

i can not run the code, when i call iClose("EURUSD", 1, 0) in python, and the MT4 crashed. there are many mistakes in the code.

**Comment by rmawatson** [comment]
"there are many mistakes in the code."
Fix,
Commit,
Push then
