### ISSUE TITLE
OnOrderHandler doesn„t fire when a new order is placed

### ISSUE THREAD

**Issue by claudiutraistaru** [rmawatson/PyMT4#9]
From the example everything is ok on OnOrderManager , it is able to read the orders , but OnOrderHandler doesn„t register new orders. I am unable to find where the problem is.

**Comment by rmawatson** [comment]
This was just a random example, and may not be perfect. But, OnOrderHandler is just a method that is called when a new ticket is discovered. This is not event driven, and is just polled in a while loop in a separate thread. Look at 

  @classmethod
    def __run(cls):

this polls for new orders, checks if it hasn't already seen them, then if a new order is spotted, loops over any registered handlers in cls.__handlers and calls them. You may want to add some print statements into this __run() method and see whats going on.
